[package]
name = "analyser"
version = "0.1.0"
authors = ["Jean DA COL <dacolj@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.4"
chrono = "0.4"